### ISSUE TITLE
Boxes not cropped properly

### ISSUE THREAD

**Issue by yashsandansing** [VikParuchuri/texify#3]
So I'm using the streamlit demo app to use `texify` for processing images. It seems that the boxes that you select by dragging in the canvas are not the actual boxes that are selected.

## Input Image:
![page_2](https://github.com/VikParuchuri/texify/assets/48054260/c95ff1b5-c06c-46e4-a8f1-414b04258e29)

## Output of streamlit app
![Screenshot 2023-12-26 at 13-20-40 ocr_app · Streamlit](https://github.com/VikParuchuri/texify/assets/48054260/ef543b05-5846-4664-820c-b04662d56839)

The expected output would be normal text from the cropped region:
>>> Now, stretching in front of you...

but it's selecting text from the block above the cropped region

_Note: This is just an issue with cropping in streamlit. If I crop the image, and use the `OCR Image` button, the OCR works fine_

**Comment by VikParuchuri** [comment]
Thanks for the report.  I'll look into this.  I've done more testing with PDFs than images, it's probably due to resolution being scaled.

**Comment by VikParuchuri** [comment]
This should be fixed now.  Try `pip install -U texify` to update to the new version.
