### ISSUE TITLE
Model weights are not automatically downloaded

### ISSUE THREAD

**Issue by shalimujiang** [VikParuchuri/texify#4]
![image](https://github.com/VikParuchuri/texify/assets/75249643/b9f3a554-903c-42ab-84d6-b0d002975c87)
Hi the first time I ran this project without automatically downloading model weights how should I get that I first used poetry.

**Comment by VikParuchuri** [comment]
That's odd - do you have a firewall that blocks huggingface?  You can try pinging huggingface.co.  If so, you can follow the instructions in the link in the error message to download the `vikp/texify` model, then set `MODEL_CHECKPOINT=path_to_model` as an env var.

**Comment by shalimujiang** [comment]
> That's odd - do you have a firewall that blocks huggingface? You can try pinging huggingface.co. If so, you can follow the instructions in the link in the error message to download the `vikp/texify` model, then set `MODEL_CHECKPOINT=path_to_model` as an env var.这很奇怪 - 你有阻止拥抱的防火墙吗？您可以尝试 ping Huggingface.co。如果是这样，您可以按照错误消息中的链接中的说明下载 vikp/texify 模型，然后将 MODEL_CHECKPOINT=path_to_model 设置为环境变量。



> That's odd - do you have a firewall that blocks huggingface? You can try pinging huggingface.co. If so, you can follow the instructions in the link in the error message to download the `vikp/texify` model, then set `MODEL_CHECKPOINT=path_to_model` as an env var.

Thank you for your reply. I will do what you said, and now it can be run successfully. Thank you for your open source, thank you.

**Comment by VikParuchuri** [comment]
Glad to hear it helped!
