### ISSUE TITLE
Can you release code fine-tuning for this model

### ISSUE THREAD

**Issue by TuanAnhNguyen14111998** [VikParuchuri/texify#5]

**Comment by VikParuchuri** [comment]
Hi, this is trained on top of donut, but with a custom image processor.  You can find the image processor in this repo, and then fine-tune similarly to donut tutorials like this - https://github.com/NielsRogge/Transformers-Tutorials/blob/master/Donut/DocVQA/Fine_tune_Donut_on_DocVQA.ipynb
