### ISSUE TITLE
support for other languages 

### ISSUE THREAD

**Issue by BenEcon** [VikParuchuri/texify#8]
It is a wonderful package, the ocred result is much better than expected. Thank you for your great job. I have one question. How to support other languages from model, or from other open source package, for example pytesseract?

**Comment by VikParuchuri** [comment]
The tokenizer is unfortunately english-only, and would have to be extended for other languages.  Not very difficult, but will take some time to implement.  It's not in my plans currently, but I may separately end up training a multilingual OCR model that support LaTeX.

**Comment by BenEcon** [comment]
That is great, wait for it.

**Comment by EnzoWuu** [comment]
> The tokenizer is unfortunately english-only, and would have to be extended for other languages. Not very difficult, but will take some time to implement. It's not in my plans currently, but I may separately end up training a multilingual OCR model that support LaTeX.

I can help with the work on the Chinese model, if you need it.
